Burnchart
Wikimedia-Sverige/scripts pull request #3
Opened 2019-10-21 10:34 UTC by lokal-profil

Add burnchart script and re-arrange google drive scripts

2019-10-23 07:11 UTC, sebastian-berlin-wmse requested changes
Looks mostly fine. I didn't run the actual code since I don't have source data, so it's just general syntax stuff.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on README.md
> +  * calc_burnchart.gs - "Script for the Burnchart document. Used to copy tab name
Replace " with *.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +function getSheetName(ref, trigger) {
Could the names for `ref` and `cell` be switched? It reads like the parameter is a cell and that the call in the function gets a reference.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +}
This could be moved down to line 48, since it's only used `returnFormulaArgs`.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +var delimiterLookup = {
`delimiterMap` would be a more conventional/transparent name.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +function returnFormulaArgs(formula) {
Rename function to `getFormulaArgs`.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +// extract cell reference formula arguments
Turn this (and similar comments below) into fully fledged "doc string" like some functions have.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +    for (i = 0; i < args.length; i++) {
Use `var i` to keep the variable in the scope.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +    for (i = 0; i < args.length; i++) {
Same for a few other for loops below.

2019-10-23 07:11 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +    if (percent.length == 0) {
Change to `===`.

2019-11-01 19:04 UTC, lokal-profil commented on google_drive_scripts/calc_burnchart.gs
> +// extract cell reference formula arguments
I've reserved the fully fledged docstrings for the custom functions. I.e. the functions that are callable from the spreadsheet (and where the docstring is displayed as a tooltip)

2019-11-04 16:20 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +// extract cell reference formula arguments
OK, that makes sense.

2019-11-04 16:27 UTC, sebastian-berlin-wmse commented on google_drive_scripts/calc_burnchart.gs
> +    for (i = 0; i < args.length; i++) {
There's one more loop on line 124.

2019-11-20 22:59 UTC, lokal-profil commented on google_drive_scripts/calc_burnchart.gs
> +    for (i = 0; i < args.length; i++) {
Good spot. Handled

2019-11-21 15:58 UTC, sebastian-berlin-wmse approved these changes

2019-11-21 16:01 UTC, sebastian-berlin-wmse commented
It looked like the last commit removed the end-of-file new line. You can fix it if you want, but I won't require it to merge.

2019-11-22 08:41 UTC, lokal-profil commented
> It looked like the last commit removed the end-of-file new line. You can fix it if you want, but I won't require it to merge.

That is weird my local file has a newline at the end and when I `git diff origin/burnchart` I get no differences

2019-11-22 08:49 UTC, sebastian-berlin-wmse commented
It may just be Github not visualizing it correctly then.

2019-11-22 08:58 UTC, merged