Add 2023 projects
Wikimedia-Sverige/scripts pull request #34
Opened 2023-09-11 14:03 UTC by lokal-profil

2023-09-11 14:24 UTC, sebastian-berlin-wmse commented on fortnox_huvudbok_processing/projects_2023.json
> +    "231214": "Rätten till kunskap i Sverige",
If this moves down one row it would be in order.

2023-09-11 14:30 UTC, sebastian-berlin-wmse commented on fortnox_huvudbok_processing/projects_2023.json
> +    "234501": "MP - Föreläsningar 2023"
The number is the same as on two rows above. Guessing this is an unintentional duplicate.

2023-09-11 14:30 UTC, sebastian-berlin-wmse commented on fortnox_huvudbok_processing/projects_2023.json
> +    "234400": "Internationella fri kunskapsrörelsen 2023",
If this moves up two rows it would be in order.

2023-09-11 14:35 UTC, sebastian-berlin-wmse requested changes
I checked the 23... projects against the project table and they look right.

The duplicate should be fixed. Sorting by project number is up to you; it may catch things like that.

2023-09-12 08:12 UTC, lokal-profil commented
> I checked the 23... projects against the project table and they look right.
> 
> The duplicate should be fixed. Sorting by project number is up to you; it may catch things like that.

Thanks for catching the dupe! Sorting while I'm at it.

2023-09-12 11:25 UTC, sebastian-berlin-wmse approved these changes

2023-10-02 12:49 UTC, merged